# Generated by Django 3.1.1 on 2020-09-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20200928_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
