# Generated by Django 3.1.1 on 2020-09-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_election'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='election',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
