# Generated by Django 3.1.1 on 2020-09-28 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20200928_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 28, 10, 15, 27, 695315)),
        ),
    ]
