# Generated by Django 3.1.1 on 2020-09-28 10:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20200928_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 28, 10, 38, 56, 262576, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='voter',
            name='uuid',
            field=models.UUIDField(default='f0fa662f', editable=False),
        ),
    ]
