# Generated by Django 3.1.1 on 2020-09-28 11:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20200928_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='avatar',
            field=models.ImageField(default='candidate/default.png', upload_to='candidate'),
        ),
        migrations.AddField(
            model_name='vote',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 28, 11, 5, 58, 441995, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='election',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 28, 11, 5, 58, 440618, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='voter',
            name='uuid',
            field=models.CharField(default='56bceb85a00b', editable=False, max_length=64),
        ),
    ]
