# Generated by Django 3.1.1 on 2020-09-28 11:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20200928_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='avatar',
            field=models.ImageField(default='static/candidate/default.png', upload_to='candidate'),
        ),
        migrations.AlterField(
            model_name='election',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 28, 11, 24, 36, 237493, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vote',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 28, 11, 24, 36, 238836, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='voter',
            name='uuid',
            field=models.CharField(default='e627e4bc5f48', editable=False, max_length=64),
        ),
    ]
