# Generated by Django 3.1.1 on 2020-09-28 11:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20200928_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 28, 11, 24, 43, 369541, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vote',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 28, 11, 24, 43, 370891, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='voter',
            name='uuid',
            field=models.CharField(default='f9f3f00d3139', editable=False, max_length=64),
        ),
    ]
