# Generated by Django 3.1.1 on 2020-10-01 17:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20201001_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 1, 17, 1, 27, 601612, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vote',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 1, 17, 1, 27, 602994, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='voter',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4901b479-0959-4686-91f2-8432912cc17e'), editable=False),
        ),
    ]
